kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: compile
        image: elixir
        commands:
            - touch config/config.secret.exs # need included file to be present, even if empty
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=test mix do deps.get --only test, deps.compile, compile
    -   name: test
        image: elixir
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - mix test --no-start --color

trigger:
    branch:
        - master
