kind: pipeline
name: default
type: docker

steps:
    -   name: compile
        image: elixir
        commands:
            - elixir -v
            - cp config/config.drone.exs config/config.secret.exs
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=test mix do deps.get --only test, deps.compile, compile
    -   name: test
        image: elixir
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - mix test --color

trigger:
    branch:
        - master
        - drone

services:
    - name: ircd
      image: inspircd/inspircd-docker
      environment:
        INSP_OPER_PASSWORD_HASH: cNkbWRWn\$MhSTITMbrCxp0neoDqL66/MSI2C+oxIa4Ux6DXb5R4Q
        INSP_ENABLE_DNSBL: no
        INSP_OPER_SSLONLY: no
