kind: pipeline
name: tests
type: docker

steps:
    -   name: compile
        image: elixir:1.10.1-alpine
        commands:
            - cp config/config.drone.exs config/config.secret.exs
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=test mix do deps.get --only test, deps.compile, compile
        depends_on: [ clone ]
    -   name: test
        image: elixir:1.10.1-alpine
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - mix test --color
        depends_on: [ compile ]

services:
    - name: ircd
      image: inspircd/inspircd-docker
      environment:
        INSP_OPER_PASSWORD_HASH: cNkbWRWn\$MhSTITMbrCxp0neoDqL66/MSI2C+oxIa4Ux6DXb5R4Q
        INSP_ENABLE_DNSBL: no
        INSP_OPER_SSLONLY: no

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: docker
type: docker

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/supportbot
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote

---
kind: pipeline
name: artifacts
type: docker

steps:
    -   name: collect
        image: elixir:1.10.1-alpine
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=prod mix deps.get
    -   name: upload
        image: plugins/s3-cache
        settings:
            rebuild: true
            path: artifacts/${DRONE_REPO_NAME}/${DRONE_COMMIT}/
            mount:
                - deps
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production
    -   name: flush
        image: plugins/s3-cache
        settings:
            flush: true
            flush_age: 14
            flush_path: artifacts/${DRONE_REPO_NAME}/
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production

trigger:
    event:
        - promote
