---
kind: pipeline
name: tests
type: docker

steps:
    -   name: compile
        image: elixir:1.10.2-alpine
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=test mix do deps.get --only test, deps.compile, compile
        depends_on: [ clone ]
    -   name: test
        image: elixir:1.10.2-alpine
        commands:
            - mix local.hex --force
            - mix local.rebar --force
            - cp .config.drone.exs config/config.secret.exs
            - mix test --color
        depends_on: [ compile ]

services:
    - name: ircd
      image: inspircd/inspircd-docker
      environment:
        INSP_OPER_PASSWORD_HASH: cNkbWRWn\$MhSTITMbrCxp0neoDqL66/MSI2C+oxIa4Ux6DXb5R4Q
        INSP_ENABLE_DNSBL: no
        INSP_OPER_SSLONLY: no

---
kind: pipeline
name: docker
type: docker

platform:
    arch: amd64

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/supportbot
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote

depends_on:
    - tests
