kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: compile
        image: elixir
        commands:
            - cp config/config.drone.exs config/config.secret.exs # need included file to be present
            - mix local.hex --force
            - mix local.rebar --force
            - MIX_ENV=test mix do deps.get --only test, deps.compile, compile
    -   name: ircd
        image: inspircd/inspircd-docker
        environment:
            INSP_OPER_PASSWORD_HASH: cNkbWRWn\$MhSTITMbrCxp0neoDqL66/MSI2C+oxIa4Ux6DXb5R4Q
        detach: true    
    -   name: test
        image: elixir
        commands:
            - sleep 5 # wait for ircd to start accepting connections
            - mix local.hex --force
            - mix local.rebar --force
            - mix test --color

trigger:
    branch:
        - master
        - drone
